# Generated by Django 5.1.2 on 2024-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('W', 'Work'), ('P', 'Personal')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('C', 'Completed')], default='P', max_length=1)),
            ],
        ),
    ]
